version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Tokyo"
    target-branch: "master"
    ignore:
      - update-types: ["version-update:semver-major"]
